name: pretty_video_player
description: Pretty Player UI with video_player plug-in
repository: https://github.com/scadasystems/Pretty-Video-Player
homepage: https://github.com/scadasystems/Pretty-Video-Player

version: 0.0.3

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.16.2"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.1
  provider: ^6.1.2
  # wakelock: ^0.4.0
  wakelock_plus: ^1.2.5
  # universal_html: ^2.2.4
  dio: ^5.4.3+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

topics:
  - video-player
